version: '3'
services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_TOKEN: ${INFLUXDB_INIT_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
  
  # simulator:
  #   build: ./simulator
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=${INFLUXDB_URL}

  # anomaly_detector:
  #   build: ./detector
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=${INFLUXDB_URL}
  #     - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
  #     - INFLUXDB_ORG=${INFLUXDB_ORG}

volumes:
  influxdb_data:
  influxdb_config: