version: '3.3'
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token

      DOCKER_INFLUXDB_INIT_MODE: ${DOCKER_INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
  
  # simulator:
  #   build: ./simulator
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=${INFLUXDB_URL}

  # anomaly_detector:
  #   build: ./detector
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=${INFLUXDB_URL}
  #     - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
  #     - INFLUXDB_ORG=${INFLUXDB_ORG}
secrets:
  influxdb2-admin-username:
    file: ./.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./.env.influxdb2-admin-token
volumes:
  influxdb_data:
  influxdb_config: